### ISSUE TITLE
Great stuff -- How is "added" defined?

### ISSUE THREAD

**Issue by cmunk** [johman10/flood-for-transmission#1]
Hi -- I have a workflow where I would like to remove torrents more than 14 days since completed. I can assume most torrents finish on the day they were Added, so maybe I can use that -- but does that persist if transmission is restarted?

And is it possible to get a column for dateDone (completed)?

**Comment by johman10** [comment]
Added would be the date that the torrent was added to Transmission. I can definitely add a column for dateDone, that should be fairly quick. Will let you know here when it's done.

**Comment by johman10** [comment]
This should be solved as per https://github.com/johman10/flood-for-transmission/commit/24242247bc7fa8526197d9de46a4914fe1a94be6.
