### ISSUE TITLE
[Feature Request] - Mobile Friend View

### ISSUE THREAD

**Issue by ondrovic** [johman10/flood-for-transmission#112]
In it's current state it isn't really usable on a mobile device, would be awesome to have an optimized mobile view

**Comment by johman10** [comment]
Hi! Thanks for the input, but this is already in the plans. Please see and follow: https://github.com/johman10/flood-for-transmission/issues/67.

**Comment by johman10** [comment]
Just letting you know here as well that I just released a new version with mobile support.
