### ISSUE TITLE
Option to change the UI "Files" to per folder instead of per file.

### ISSUE THREAD

**Issue by TegarOk** [johman10/flood-for-transmission#122]
Is it possible to change the UI "Files" on options become per folder instead of per file?
For example i have folder "Pictures" and contains 01.png, 02.png, 03.png and 04.png file.
I want that like this:
--- Pictures
--------- 01.png
--------- 02.png
--------- etc
Not like this :
Pictures/01.png
Pictures/02.png
Pictures/etc
https://imgur.com/a/vwPbcJJ

It so frustrating when i found torrent with a really many files inside, i must off per file instead of folder.
Im sorry if my english is bad.

**Comment by johman10** [comment]
Hi! Thanks for the feedback! I think this is a great idea and definitely something I will consider in the future.

I will keep this issue open and close it once it's been implemented. Do expect it to take a while do, this project is really just a side project for me. :)

**Comment by johman10** [comment]
Hi! As you can see I just merged a fix for this. It's building a release right now so please update and try it out and let me know (via a new issue) if something doesn't work as expected. :)

Hope you like it!
