### ISSUE TITLE
Automatic expansion of filter options

### ISSUE THREAD

**Issue by mauexemplo** [johman10/flood-for-transmission#137]
Minor enhancement suggestion:
If the window size allows (i.e. there's significant empty space below), it would be great if the "Show all..." expansion for the "Filter by tracker" / "Filter by label" sections on the left-hand column were expanded by default upon loading, instead of being collapsed.

Thank you and congrats for this amazing UI, it's so polished and feature-packed, I go "wow" every time I look at it!

**Comment by johman10** [comment]
Hi! Thanks a lot for a great suggestion. If you don't mind me asking what would happen in this case if one category of filters would fit expanded, but the others wouldn't, would it still expand that category or does it collapse both? How about the scenario where they are expanded by default but you add a lot more, should they then collapse when they reach the limit?

As a counter suggestion to keep this simpler, would it help you if I would make the amount of default shown filters configurable? So that you can up it from 5 to 100 if you want? I can create a config for both of the categories so that you can decide yourself which one you want more of. Would that help you just as well?

**Comment by mauexemplo** [comment]
> what would happen in this case if one category of filters would fit expanded, but the others wouldn't, would it still expand that category or does it collapse both?

Great catch! I think defining a priority for which filter to have expanded or collapsed, is unavoidable. I can't think of a strong reason for either labels or trackers to be first - maybe trackers due to being supported by Transmission 2.x? You're the boss for this choice :)

> How about the scenario where they are expanded by default but you add a lot more, should they then collapse when they reach the limit?

Do you mean "add a lot more" while the interface is already loaded? If so, then this is outside the scope of my suggestion. The way I imagined it, this would be an additional check **only on initial load**. After it's already rendered and in use, I suppose it would stay in its current state (expanded or collapsed) until the user switches between them.

> As a counter suggestion to keep this simpler, would it help you if I would make the amount of default shown filters configurable? So that you can up it from 5 to 100 if you want? I can create a config for both of the categories so that you can decide yourself which one you want more of. Would that help you just as well?

This is certainly an useful config, that I can see myself fiddling with! However, I see it as a separate change, a different feature. My suggestion ("auto-expand") would apply regardless of how many filters are displayed while the section is collapsed (when it's expanded, all are shown).

----

After suggesting yesterday, I thought I had seen some interfaces (can't really recall which right now, sorry) where this was implemented *after* the initial load, after checking if the list had overflowed. If you don't mind the intrusion, maybe the steps would be:

1. Prepare containers for both filters, expanded by default
2. Load content for each filter into their containers
3. If filter area overflowed, then collapse lower priority filter container
4. If filter area still overflowed, then collapse next filter

I apologize if this is going too far, I definitely do not mean to meddle. However you wish to implement this, if you really want to, would be amazing. My intention is just to describe one way I've seen this done, as a reference.

**Comment by johman10** [comment]
Hi! I have been thinking about this a lot the last couple of weeks and honestly I think this feature is really minor and the implementation of it would be quite big. For that reason I rather put my focus on other things instead.

That said I really appreciate your input and thinking with me here.

I will close this issue for now, but when I really don't know how to make Flood for Transmission better anymore, I might just come back to this. :)
