### ISSUE TITLE
iOS right-click menu access

### ISSUE THREAD

**Issue by pkishino** [johman10/flood-for-transmission#241]
Sorry for opening this as an issue..I really like flood and use it, but it is a bit of a hassle on the mobile front (ios 14+15) because I cannot access the right click menu anyway.. click and hold for slightly longer should work but doesnt..
I'd like to easily delete/move torrent location on the go.
Please let me know if there is a way or if this needs fixing.
cheers

**Comment by johman10** [comment]
Don't worry about opening an issue! This is my only feedback on people using this UI, so I kind of love hearing from people that actually use it! :D

This is interesting though. I believe this should work. In the responsive mode of Google Chrome it seems to work, but that's not always a good indicator.

Do you have any idea what could be going wrong and/or the option to debug this a little further? I don't own an iPhone and for me on Android it works perfectly fine with a long press. If you don't have the ability to look at this further I can hunt down some documentation at some point.

**Comment by pkishino** [comment]
if I try to long press it tries to select the text of the name..double tap opens the torrent details window.. two finger tap/press doesnt do anything..I checked responsive mode in macos chrome and there long press works..safari as well..but on ios/iphone, nope

**Comment by johman10** [comment]
Alright, thanks for diving a little deeper. I will have a look at this when I find some time. :)

**Comment by johman10** [comment]
I had a little bit of a look at this and it seems a common issue around the web. The cleanest solution I bumped into with a 5 minute search was this: https://codesandbox.io/s/react-ios-oncontextmenu-bug-f34j1?file=/src/ContextMenuHandler.js. Perhaps worth implementing it so that this works for everyone.

I will have further look some other times. Just documenting my findings. :)

**Comment by johman10** [comment]
With the latest release this should be resolved! :D
