### ISSUE TITLE
Setting label just hangs

### ISSUE THREAD

**Issue by SenorSmartyPants** [johman10/flood-for-transmission#243]
This used to work fine, but is now hanging. It is happening on the https://github.com/haugene/docker-transmission-openvpn image I run. I'll gladly provide logs, but not sure where to look at the moment.

Still works fine on https://hub.docker.com/r/linuxserver/transmission

**Comment by SenorSmartyPants** [comment]
![image](https://user-images.githubusercontent.com/991618/132253429-9a17ea28-3643-42a5-a012-33dc1b630c92.png)

This seems odd as well. All torrents both "Unlabeled" and "undefined"

**Comment by johman10** [comment]
Hi! Thanks for reaching out.

I'm not 100% certain what's going on here. I wasn't able to reproduce this right now. Almost feels like your transmission torrents have been set up in a weird way before. Did you run another UI before you started using Flood for Transmission? Did you use labels in that UI? Also, is this in a specific browser or do you see this behavior consistently in all browsers?

Hope to gather some more info on this before I can work on this.

**Comment by SenorSmartyPants** [comment]
The only UI I've used with label support is flood.

But my torrents info did get corrupted(?) recently. Transmission forgot the directory location I'd set on individual torrents, all were pointing to main dl directory. I was able to just set that back to the way I wanted using flood.

Where is the label saved? Maybe I can shut down the server, wipe label info and then UI will work again?

**Comment by johman10** [comment]
The labels are stored in Transmission on the torrent. It depends on the labels that can be set like documented here: https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt#L120.

Are you still able to double click on a torrent to see more details? What does it show there under labels? Also undefined?
![2021-09-08_12-42](https://user-images.githubusercontent.com/5371454/132486491-da149949-4ce2-4e6c-96d0-ade7c4ea3dff.png)

If it does show undefined that would mean that your data is somehow not correct. In that case maybe I can somehow guide you through updating all torrents by calling the endpoint I linked somehow.

**Comment by SenorSmartyPants** [comment]
Yes, I can still double click to open details. Labels show as blank

![image](https://user-images.githubusercontent.com/991618/132564390-aca25753-437d-42c4-b7dd-44f32299212f.png)

I tried to set a label on a torrent I downloaded today, still hangs. I've restarted docker container a few times, doesn't make a difference.

**Comment by SenorSmartyPants** [comment]
I think all my issues are because of this:
https://github.com/haugene/docker-transmission-openvpn/discussions/1936

Image downgraded to transmission 2.95 from 3.0. 

I rolled back to transmission 3.0 and labels started showing up again.

**Comment by johman10** [comment]
Aha, that would be correct. Labels are only supported since Transmission 3.0. You can see that here: https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt#L819-L820.

I didn't expect that to be the cause because you were running the docker image. I wasn't aware that they decided to downgrade because of UI issues.

I'm sorry but I don't really have an interest in supporting multiple API version with this project. I hope that's not a problem for you. Maybe you can run on https://hub.docker.com/r/linuxserver/transmission with the flood-for-transmission UI until https://github.com/haugene/docker-transmission-openvpn has been updated?

**Comment by SenorSmartyPants** [comment]
I'm staying on 3.0. So I'm all good. Thanks
