### ISSUE TITLE
Request for Optional Color Swap

### ISSUE THREAD

**Issue by KWall24** [johman10/flood-for-transmission#264]
I'd like to request a checkbox in the settings to swap the Green (download) and Blue(upload) for Blue(download) and Green(upload). Alternatively, let me know how I can make this change for myself.

Most clients (including Transmission) use green color to show a file seeding, and many will show blue for downloading. I love Flood, but it's currently backwards as far as I'm concerned.

That being said, green I don't think would work as the "highlight" color for the menus, so I'd just want the colors on the graphs and stats in the top left corner and the bars/number in the torrent list to swap their greens and blues.

Thanks for this awesome skin!

**Comment by johman10** [comment]
Hi! I just shipped a new version which includes this feature.

After you update Flood for Transmission you can go into the settings, user interface and check the checkbox that will switch the colors. Don't forget to save and you're all good!

I hope this helps, let me know if something isn't working as expected.
