### ISSUE TITLE
Allow sorting on torrent columns

### ISSUE THREAD

**Issue by cmunk** [johman10/flood-for-transmission#3]
It seems it's not implemented yet to sort on torrent columns?

**Comment by johman10** [comment]
It's not, has been on the list though. Will probably get to this soon. Thanks for the request. Will let you know when I found time to look at this! :)

**Comment by johman10** [comment]
I just implemented this as per: https://github.com/johman10/flood-for-transmission/commit/4887004c0348157a1ca69a92f57065dcc7620d55
