### ISSUE TITLE
Missing Force Start option

### ISSUE THREAD

**Issue by KamikazeePL** [johman10/flood-for-transmission#303]
There is missing **Force Start** option on torrent file.

**Comment by johman10** [comment]
@KamikazeePL I don't know about this feature. Could you confirm that it's this action?
https://github.com/transmission/transmission/blob/master/extras/rpc-spec.txt#L104

If so that would mean "Force start" would start the torrent an bypass the possible queue

**Comment by KamikazeePL** [comment]
Yes this option

**Comment by johman10** [comment]
I just added the above linked PR. It should resolve this issue.

Let me know if it doesn't work as expected.
