### ISSUE TITLE
Add "Queue Position" column

### ISSUE THREAD

**Issue by davdroman** [johman10/flood-for-transmission#312]
I miss this from other Transmission GUIs. It'd be super helpful to be able to sort transfers by Queue Position.

**Comment by johman10** [comment]
Hi! Thanks for the feedback, I will add a column for this soon-ish.

**Comment by davdroman** [comment]
@johman10 thanks for your response. Good to know it's on the roadmap.

I really appreciate all the work you're doing btw 👏  please consider accepting donations, I'd love to be able to give back.

**Comment by johman10** [comment]
@davdroman thanks a lot for the encouraging words and your willingness to donate. I will see if I can come up with a way to make that easy for everyone. And update you here if I found a way. Please consider staring the repository if you like it though, that way other people might find it easier too.

As per the above PR this should now be resolved, I hope it works as expected for you, but please let me know if it doesn't. :)

**Comment by davdroman** [comment]
@johman10 excellent! Thanks again for this.

A simple solution to donations would be to enable GitHub Sponsors for this repo (from Settings). In my experience as a donor, it's extremely convenient.

**Comment by johman10** [comment]
Hi @davdroman!
I just wanted to let you know I was able to enable Github Sponsors on this repo. If you're still willing to support my work, you can now do that.

No pressure though! :)
