### ISSUE TITLE
Flood w/ Transmission 3.0.0 on MacOS install issue

### ISSUE THREAD

**Issue by FoUStep** [johman10/flood-for-transmission#330]
The only way I could get Flood to work with the default Transmission app for MacOS (no brew, just the dmg download on the site) was by downloading the flood-for-tranmission.zip, opening the package contents of Transmission.app and renamed the current web folder to web.old and created a new folder called web, inserted the contents of the flood-for-transmission.zip and restarting the app.

The location of the web folder:
`/Applications/Transmission.app/Contents/Resources`

I tried  ~/.zprofile (created it) and  ~/.zshrc (MacOS default) with adding the export command (including required restarts) but to no avail. Please update the manual for MacOS, or perhaps tell me how to make this work on CLI. Willing to test.

**Comment by johman10** [comment]
Hi! Thanks for pointing this out. I did some searching and found that you're correct. The readme approach won't really work, it basically hasn't worked like that since Mac switched to zsh as the default I believe.

I think the correct way might be as described by [this comment on Stackoverflow](https://stackoverflow.com/a/3756686). I don't have a Mac so I can't really try it out. Would you mind trying it for me? It would probably be something like:
```
# To try it once, should apply for any newly started application after this so restart Transmission after it
launchctl setenv TRANSMISSION_WEB_HOME /path/to/your/flood-for-transmission

# To maintain the variable, should apply after a reboot so restart your computer after this and check if Transmission works
launchctl config user TRANSMISSION_WEB_HOME /path/to/your/flood-for-transmission
```

While your method works I think it's nicer to give the users of this UI the freedom to choice where to put Flood for Transmission.

Do let me know what you find or if you don't want to try this out. ;)

**Comment by johman10** [comment]
Thanks a lot for trying! Apparently that didn't work, so yeah, perhaps it's nicest to just update the README to instruct the user to do what you did and rename the old folder. Perhaps I will leave a note asking for anyone that knows a better to let me know. I will also add a note to mention that any update of Transmission will overwite the web UI.

Thanks again, I will update the README soon-ish.

**Comment by FoUStep** [comment]
If you need me to do more testing, let me know. Thanks for your time and creating a great web interface for Transmission.

**Comment by johman10** [comment]
Hi! I bumped into a possible alternative. If you have time could you give it a go? Does it work when you run the following in the CLI?
```
# Replace path with your local path
open /Applications/Transmission.app --args -TRANSMISSION_WEB_HOME "/path/to/flood-for-transmission"
 ```

If that doesn't work would you mind also trying with an = between the TRANSMISSION_WEB_HOME variable and the value? Or remove the `-` before the variable?

If this work I think you should be able to create script that will run Transmission instead. Perhaps still not better anyway, but at this point I'm just curious. ;)
 
 Sourced from: https://github.com/transmission/transmission/issues/1742

**Comment by FoUStep** [comment]
So I tried everything you suggested, unfortunately it did not work. I even tried my own variations (extra -, less -, added '', removed "", added = etc etc) but to no avail.

It does not error, it just starts Transmission but it still has the original web interface.

**Comment by johman10** [comment]
Thanks again for testing. I updated the README instructions. Feel free to let me know if something is still unclear!
