### ISSUE TITLE
Add "Last active" column

### ISSUE THREAD

**Issue by Kanjirito** [johman10/flood-for-transmission#346]
Transmission provides `activityDate` ("The last time we uploaded or downloaded piece data on this torrent") which is a useful way to sort torrents, especially when you have many of them. The name could be just "Activity" to be more in line with "Added" and "Ended".

**Comment by Kanjirito** [comment]
I've noticed now that this would need to display the date differently than "Added" and "Ended" to be properly useful. It should also show the hour and minute (maybe even seconds).
Or maybe `DateRenderer` as a whole should also display the time too but I'm not very sure about that.

**Comment by johman10** [comment]
Both of these points should be handled now.
