### ISSUE TITLE
Done date as UI column?

### ISSUE THREAD

**Issue by mseeley** [johman10/flood-for-transmission#350]
Hi there 👋😄.

It would be helpful to see the date a torrent finished downloading in the grid.

I believe UI support for a Done date column was added [~13 months ago](https://github.com/johman10/flood-for-transmission/commit/24242247bc7fa8526197d9de46a4914fe1a94be6). Although the interesting part is that I don't [see the date locally](https://user-images.githubusercontent.com/30019/152112499-e8d59753-a358-440f-83e2-5bcf4022759a.png). 

"Locally" is a container running `linuxserver/docker-transmission`. I _believe_ the container setup [pulls the latest](https://github.com/linuxserver/docker-transmission/blob/03dfc65a0c5b07d301de13f828f68f056481b70f/Dockerfile#L57-L59). FFT was [added in 06.03.21](https://docs.linuxserver.io/images/docker-transmission#versions).

I can't find a version/hash/release in the `Flood > Settings > About` modal. Also having trouble finding a FFT release token in the `build/` assets, these hashes are the closest as I've found.  The hash suffixes on the file names don't seem to link to commits in this repo.

```
root@37b210e7957d:/flood-for-transmission/build# ls -l
total 872
-rw-r--r-- 1 abc 121   1769 Dec 11 00:40 About-da315213.js
-rw-r--r-- 1 abc 121   1376 Dec 11 00:40 About-da315213.js.map
-rw-r--r-- 1 abc 121    465 Dec 11 00:40 Header-95a6de66.js
-rw-r--r-- 1 abc 121    378 Dec 11 00:40 Header-95a6de66.js.map
-rw-r--r-- 1 abc 121   3896 Dec 11 00:40 Network-3d63c14c.js
-rw-r--r-- 1 abc 121   5253 Dec 11 00:40 Network-3d63c14c.js.map
-rw-r--r-- 1 abc 121   5942 Dec 11 00:40 Peers-0752808f.js
-rw-r--r-- 1 abc 121   7793 Dec 11 00:40 Peers-0752808f.js.map
-rw-r--r-- 1 abc 121   6105 Dec 11 00:40 Speed-01b0c589.js
-rw-r--r-- 1 abc 121   7830 Dec 11 00:40 Speed-01b0c589.js.map
-rw-r--r-- 1 abc 121   9456 Dec 11 00:40 Torrents-8a4d2a9f.js
-rw-r--r-- 1 abc 121  12159 Dec 11 00:40 Torrents-8a4d2a9f.js.map
-rw-r--r-- 1 abc 121   5663 Dec 11 00:40 UserInterface-a089e3b2.js
-rw-r--r-- 1 abc 121   7342 Dec 11 00:40 UserInterface-a089e3b2.js.map
-rw-r--r-- 1 abc 121  40941 Dec 11 00:40 bundle.css
-rw-r--r-- 1 abc 121 225567 Dec 11 00:40 main.js
-rw-r--r-- 1 abc 121 516572 Dec 11 00:40 main.js.map
```

Took a guess and looked for the `export` values added in 24242247bc7fa8526197d9de46a4914fe1a94be6. No success. Maybe they're compiled out?

```
root@37b210e7957d:/flood-for-transmission/build# grep UI_COLUMN_DONE *.js
root@37b210e7957d:/flood-for-transmission/build# grep TRANSMISSION_COLUMN_DONE *.js
```

Will you please help me figure out if there's a release token expected in the release bundle downloaded from GitHub?

I'll try and update this container. Are there other possible explanations for a missing `Done` column?

Thanks so much for your input. :)

**Comment by mseeley** [comment]
Oh boy, `Done` is right there in the screen shot. Apologies for the noise. 😳 😅

**Comment by johman10** [comment]
No worries! Glad to see you found it! :D
