### ISSUE TITLE
Show exact date and time when added + Adjust the Encryption settings

### ISSUE THREAD

**Issue by milesbarry** [johman10/flood-for-transmission#355]
Hi,

Firstly absolutely love the interface, and thank you for developing it!

Two features I'd like to see is the date and time when the torrent was added, not just the date as it currently is.

Also the ability to control the encryption settings as per

https://github.com/transmission/transmission/wiki/Editing-Configuration-Files#misc

Hope this is easily doable. 

Best wishes!

**Comment by johman10** [comment]
Good input, I will have a look at both!

**Comment by milesbarry** [comment]
> Good input, I will have a look at both at some point!

Hi , thanks. I certainly think the setting of encryption would be very beneficial. It's the only setting I needed to tweak in the settings.conf, for the rest of it your wonderful UI did everything.

Best wishes!

**Comment by johman10** [comment]
Both or your wishes should be fullfilled in the latest release! 🧞 

Please let me know if something doesn't work. :D
