### ISSUE TITLE
Ideas - Show % downloaded without having to click & Show public IP in use

### ISSUE THREAD

**Issue by milesbarry** [johman10/flood-for-transmission#360]
Would be nice to see more clearly the % downloaded rather than just the progress bar. Perhaps if you hover over it, or you place the % within or on the progress bar area.

Another idea is to show the current public IP address being used by periodically doing something like

dig +short myip.opendns.com @resolver1.opendns.com

I'd personally place this in the left panel with the network up and down speeds.

Best wishes

**Comment by johman10** [comment]
> Would be nice to see more clearly the % downloaded rather than just the progress bar. Perhaps if you hover over it, or you place the % within or on the progress bar area.

As you can see I now added a PR to add a new column for the % downloaded in text. I hope that will help you once it's shipped.

> Another idea is to show the current public IP address being used by periodically doing something like
>
> dig +short myip.opendns.com @resolver1.opendns.com
>
> I'd personally place this in the left panel with the network up and down speeds.
This won't be possible, at least not without another API call to get the data from some service. "Digging" through hostnames isn't possible in JS, so I would have to find an API to request this data from and I consider that too much effort for such a small detail.

I would recommend you to look into other ways of visualizing which IP address you're using if that's what you're looking for.

Thank you for you input and I hope you're at least happy to see the Percentage as text in a column. :)

**Comment by notoriousjere** [comment]
@johman10 Thanks for directing me here. I'd be totally happy with the new dedicated column. I have to say, I did find it ironic that there was a column labeled "Percent Complete" that did not display a percentage 😂.

Thanks for the quick update on this!
