### ISSUE TITLE
Mobile UI

### ISSUE THREAD

**Issue by eximo84** [johman10/flood-for-transmission#379]
I'm using Linux server docker container for transmission and it uses flood-for-transmission. 

https://docs.linuxserver.io/images/docker-transmission

I've updated latest version of the container, also manually pulled the zip from the releases inside the container but the mobile UI isn't showing. Instead I have the desktop UI. 

I saw a closed issue on the Linux server GitHub page saying the mobile UI was just making it respond to touch rather than a full UI change?

**Comment by johman10** [comment]
> I saw a closed issue on the Linux server GitHub page saying the mobile UI was just making it respond to touch rather than a full UI change?

What kind of full UI change are you expecting? Mobile UI will look the same as on desktop, it just supports touch and the drawer (the thing with the graph on the left) will flow over the list rather than to take up space all the time.

**Comment by eximo84** [comment]
https://flood.js.org/assets/img/screenshot-mobile-expanded-dark.jpg

Mobile is touch friendly but not responsive as per the screenshot from the flood webpage.

**Comment by johman10** [comment]
That screenshot isn't from this project. That is a screenshot from https://github.com/jesec/flood. It's a similar project than this, but more feature heavy and support for other P2P clients.
