### ISSUE TITLE
Provide Container Image

### ISSUE THREAD

**Issue by Preisschild** [johman10/flood-for-transmission#383]
I think it would be a good addition to provide flood for transmission as a container image.

We can write a Dockerfile, use the [k8s-at-home Transmission Container Image](https://github.com/k8s-at-home/container-images/pkgs/container/transmission) as the base and just copy flood to the right directory.

Fortunately Github provides the Github Container Registry, so we can provide the built container image directly on Github.

The most used architectures are `amd64` and `arm64`, so we should try to provide images for both. The transmission image from kah also provides both.

**Comment by johman10** [comment]
Transmission ships with the following docker images already:
https://hub.docker.com/r/linuxserver/transmission
https://hub.docker.com/r/haugene/transmission-openvpn

I have no intention to set up my own docker image, but I'm willing to contribute to that k8s-at-home repo to add flood-for-transmission there as well. However, if you feel especially inspired feel free to contribute to those projects yourself. Let me know if you do so. :D

**Comment by johman10** [comment]
As you can see I opened a PR. Let's see what the maintainers of container-images think of the changes. :)

**Comment by onedr0p** [comment]
@Preisschild see my comment in https://github.com/k8s-at-home/container-images/pull/203
