### ISSUE TITLE
Copy magnet link

### ISSUE THREAD

**Issue by KamikazeePL** [johman10/flood-for-transmission#386]
**Copy magnet link** doesn't copy magnet link to clipboard, tested on Windows 10 on Firefox and Egde browser

**Comment by johman10** [comment]
Interesting that this doesn't work for you. I will have to try myself to see if I can reproduce it. It might be that my solution for the copying is too Chrome specific, it's always worked for me there.

Either way, I will have a look at some point.

**Comment by johman10** [comment]
Hi,
I just tried this on Windows 11 in Chrome, Edge and Firefox and all of them seem to behave correctly when using this button.
![image](https://user-images.githubusercontent.com/5371454/163435022-97fb764c-95c4-4d46-9663-ec95b94b0594.png)

Would you be able to provide more details? Do you know how to open the JS console? Do you see any message there? Do you see the notification in the right bottom telling you that copying succeeded?

Please let me know when you have a moment. :)

**Comment by KamikazeePL** [comment]
In Firefox
Uncaught TypeError: navigator.clipboard is undefined
    copyMagnetLinks http://myip:9091/transmission/web/build/main.js:1
    ia http://myip:9091/transmission/web/build/main.js:1
    ga http://myip:9091/transmission/web/build/main.js:1

**Comment by johman10** [comment]
Aha, it seems like it's because you're on the HTTP protocol instead of HTTPS, which is what I'm using. This could use some fixing, probably based on this: https://stackoverflow.com/a/65996386.

I will have a look soon!
