### ISSUE TITLE
Feature request: option to show a percentage in the "percent complete" column

### ISSUE THREAD

**Issue by notoriousjere** [johman10/flood-for-transmission#387]
Currently the "percent complete" column is just a progress bar. I find satisfaction in seeing a percentage as well. Do you think you could add a checkbox to enable or disable a percentage number in this column? Alternatively, add an entirely new column that only shows percentage.

**Comment by johman10** [comment]
There was a similar request here:
https://github.com/johman10/flood-for-transmission/issues/360

Please follow that thread for future updates. I would probably add another column instead. It's easier than to add it to the existing progress bar column.
