### ISSUE TITLE
Unable to get Transmission to recognize web files

### ISSUE THREAD

**Issue by jandreaucodes** [johman10/flood-for-transmission#402]
I just upgraded to a nightly build to get native M1 support, but seem to have lost the TRANSMISSION_WEB_HOME configuration.

I've followed all of the instructions to get Flood running and still get this error:

`404: Not Found
Couldn't find Transmission's web interface files!

Users: to tell Transmission where to look, set the TRANSMISSION_WEB_HOME environment variable to the folder where the web interface's index.html is located.`

I've confirmed that Flood is at /Transmission.app/Contents/Resources/web

I tried forcing the TRANSMISSION_WEB_HOME to be set via:

` open /Applications/Transmission.app --args -TRANSMISSION_WEB_HOME "/Applications/Transmission.app/Contents/Resources/web"`
and 
` % open /Applications/Transmission.app --args -TRANSMISSION_WEB_HOME="/Applications/Transmission.app/Contents/Resources/web"`

I've tried forcing the transmission-daemon to run in case that's what controls the web GUI. But none of it works.

Any help is appreciated in getting Transmission to recognize the files for the web GUI, so I can use Flood.

**Comment by johman10** [comment]
Does the folder at `/Transmission.app/Contents/Resources/web` contain and index.html file?

Could it have to do with the nightly build? Is something broken there? If you downgrade to version 3.00 does it work then?

**Comment by jandreaucodes** [comment]
Yep, there's an index.html file in there. 

I downgraded, but must have a bad plist file because it doesn't work with 3.0, either.

**Comment by johman10** [comment]
Hmm.. not sure how I can help you, do you still have the original UI around? If you put that back does it start working again?

**Comment by jandreaucodes** [comment]
It doesn't, no. Gotta be something with my Transmission configuration then. Just don't know what to do to get Transmission to recognize those files. I'll keep poking, thanks.
