### ISSUE TITLE
Feature request: Add options for text wrapping behavior

### ISSUE THREAD

**Issue by notoriousjere** [johman10/flood-for-transmission#406]
Many column names are far longer than the usual contents of said column This requires the column width to be set wider than the row contents really needs -- or you can decide to cut off the column name.
![image](https://user-images.githubusercontent.com/18120535/164059105-01141c78-85fd-4986-96f8-446bb71dd7de.png) ![image](https://user-images.githubusercontent.com/18120535/164060478-aea1b478-fa8e-4fbb-961a-ce70f9babfff.png)

In order to facilitate showing more columns at the same time while trying to avoid a horizontal scroll bar, it would be very convenient to control whether or not column names are text wrapped. The behavior should be similar to common spreadsheet applications like MS Excel and Google Sheets (only break to a new line between words).

Example mockup in google sheets:
- Text is only broken to new line on spaces
- Text that doesn't require wrapping is always vertically centered
- Keep all text horizontally aligned left (this is the current behavior)

![image](https://user-images.githubusercontent.com/18120535/164060800-220dc957-1b59-4729-896e-ffdd4f654093.png)

Additionally, controlling a separate option for text wrapping within the rows of data (i.e. long torrent name) would nice as well, but less important as it might ruin the visual presentation to have rows of various heights.

---
Apologies for another Issue so soon, but I just recently found your project and I think it's super cool. Usually most torrent clients have horrible user interfaces and this is the first one that is actually a pleasure to look at. Hope you don't mind the visual nitpicking!

**Comment by johman10** [comment]
I think this is a good suggestion as long as we keep it as a setting. It shouldn't be too hard either, just apply a class on the column if something is set in localStorage and use the browser native text wrapping options on cell's.

Will have a look at this when I find some time. ;)
