### ISSUE TITLE
Feature Request: Treat the main torrent list as file "drop zone"

### ISSUE THREAD

**Issue by qhartman** [johman10/flood-for-transmission#414]
I usually download torrent files and then open them in flood by clicking +, then add file, then drag and dropping a file into the dialog. If the entire torrent list pane were treated as a file drop zone (probably in addition to the existing functionality) it would eliminate several clicks.

**Comment by johman10** [comment]
@qhartman as you can see the issue closed due to the PR I just shipped. You can now drag and drop items on the main list. If you experience any issues with this let me know.

**Comment by qhartman** [comment]
Sweet! Excited to check it out. Will let you know how it works for me.

**Comment by qhartman** [comment]
Just managed to get a new build running with the feature. Works great!
Thanks so much!
