### ISSUE TITLE
Can't move columns on Safari

### ISSUE THREAD

**Issue by justSunny12** [johman10/flood-for-transmission#427]
Hi! I really love your WebUI, but unfortunately there's no way to move and swap columns on Safari 15.4 (17613.1.17.1.13) - cursor is changing to "move" when hovering over an item, but items aren't draggable. It works fine on another browsers, but could you please fix it on Safari? As I can see, columns order doesn't save, when I set it on one browser (f.e. Chrome) then switch to another.
Thank you guys, you're awesome
<img width="486" alt="Снимок экрана 2022-05-11 в 16 28 02" src="https://user-images.githubusercontent.com/105359785/167839189-f4bf58fc-3848-4d38-9bf5-52ba7be83e91.png">

**Comment by johman10** [comment]
Hi!

Thanks for the positive feedback!

I'm sorry to hear drag and drop is not working in Safari, but since I don't really own a Mac I won't be able to debug this myself. Do you have the knowledge to have a look yourself? Ultimitatly something is probably going wrong here: https://github.com/johman10/flood-for-transmission/blob/master/src/helpers/actions/orderable.js. If you know how to open the JS console and have a look for any information there, that would already be super helpful.

Hope you (or someone else reading this) can help me debug this!

**Comment by porg** [comment]
## Workaround: Configure in Chrome, then copy/paste the value of local storage variable `ui-columns` into Safari and reload

- Open Google Crome and open your transmission server running flood-for-transmission
  - Menu > View > Developer > Developer Tools (`⌥ ⌘ I` a.k.a. "DevTools")
  - Tab "Application" > Left pane > Storage > Local Storage  > http://your-transmission-host:9091
  - In the table scroll to key `ui-columns`
  - Double click into the value field.
  - Copy the value (⌘ C)
<details><summary>It is a JSON string like this</summary>
```
[{"id":2,"enabled":true,"width":167},{"id":13,"enabled":true,"width":255},{"id":15,"enabled":true,"width":162},{"id":9,"enabled":true,"width":54},{"id":27,"enabled":true,"width":56},{"id":10,"enabled":true,"width":71},{"id":6,"enabled":true,"width":62},{"id":22,"enabled":true,"width":68},{"id":18,"enabled":true,"width":54},{"id":7,"enabled":true,"width":66},{"id":23,"enabled":true,"width":68},{"id":14,"enabled":true,"width":63},{"id":19,"enabled":true,"width":65},{"id":1,"enabled":false,"width":100},{"id":3,"enabled":false,"width":100},{"id":4,"enabled":false,"width":100},{"id":11,"enabled":false,"width":100},{"id":16,"enabled":false,"width":100},{"id":12,"enabled":false,"width":100},{"id":8,"enabled":false,"width":100},{"id":21,"enabled":false,"width":100},{"id":5,"enabled":false,"width":100},{"id":20,"enabled":true,"width":71},{"id":17,"enabled":false,"width":100},{"id":24,"enabled":true,"width":75},{"id":25,"enabled":true,"width":90},{"id":26,"enabled":true,"width":141}]
```
  </details>

- Open Safari and open your transmission server running flood-for-transmission
  - [Make sure the "Developer" menu is visible](https://support.apple.com/guide/safari/use-the-developer-tools-in-the-develop-menu-sfri20948/mac): Menu > Preferences > Advanced > Show Develop menu in menu bar
  - Menu > Developer > Show Web Inspector (`⌥ ⌘ I`)
  - Tab "Storage" > Left Pane > Local Storage > key `ui-columns`
  - Double click into the Value field. Paste the value. Hit ENTER.
  - Click the reload button in the browser (`⌘ R`)
  - Your columns in Safari are now exactly as in Chrome.

**Comment by johman10** [comment]
@porg @justSunny12 I really wouldn't know what's going wrong here until I have proper debugging information. Could one of you (or anyone else reading this) open the JS console and post the output after dragging? That would greatly help me to figure out what is failing here.

**Comment by porg** [comment]
Sorry, not installed anymore on my NAS, so I cannot test this. Good luck!

**Comment by nick2k3** [comment]
Hi, just tried on Safari  16.0 (17614.1.25.9.10, 17614) and the column reordering is not working either. 
I opened the JS Console and no error is being displayed when I try to reorder the column.
do you have an idea where I can start debugging it?

**Comment by johman10** [comment]
@nick2k3 thanks for checking! I'm not 100% sure what's going on then. Perhaps the easiest way to start debugging is to clear the local storage (or if it's easier to start a new "private window" in Safari) and visit Flood for Transmission. This should regenerate the original column configuration and might make it clearer what's going on.

Thanks for looking into this! 👏🙌

**Comment by johman10** [comment]
Hi everyone. Thanks to @kapoko this has now been resolved. If you experience further issues, please open a new issue or contribute by opening a new PR.
