### ISSUE TITLE
Add support for exporting and importing UI configuration

### ISSUE THREAD

**Issue by johman10** [johman10/flood-for-transmission#434]
There is quite a bit of config stored in the browser now. 
And @realivanjx suggested [here](https://github.com/johman10/flood-for-transmission/issues/2#issuecomment-1131884641) to add support for exporting and importing that configuration somehow.

**Comment by realivanjx** [comment]
what are config (non server config) that are stored in the browser besides the common paths?

**Comment by realivanjx** [comment]
just to keep it simple i think it is good to store everything into a `.json` file for export/import. when an export button is clicked just merge the localstorage settings into a single json object then convert to json string and then trigger a browser download dialog somehow? importing can simply be a button that open file browser dialog like the ones under Add Torrents by file. this way #427 can be mitigated while waiting for a fix.

**Comment by realivanjx** [comment]
if i am not mistaken the download thing can be done with `window.URL.createObjectURL` as explained [here](https://stackoverflow.com/a/27963891/5638260)

**Comment by johman10** [comment]
> what are config (non server config) that are stored in the browser besides the common paths? i believe currently it is everything under the User Interface menu?

Enabled and disabled columns, their width and order are also stored in LocalStorage. So that can also be part of the export.

**Comment by niawag** [comment]
Hi and thanks for this great UI, I'm using it with [transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn) as a docker container and I'd like to know if the exported json file could be mounted as a volume in docker so it could be easy to store these configs on the server.
I'm using Flood on different browsers (mobile and desktop) and it's a PITA to configure all.

**Comment by johman10** [comment]
@niawag thanks for your input!

I don't think that will be possible since the docker container won't be accessible from the browser, where the data is stored, and the browser won't be accessible from the docker container. However, if you know of some way to write to localStorage from a docker container, I'm all ears! :D

If support should be added for such a case we would have to add a feature into Transmission Daemon to support loading some UI config file from the file system. Otherwise the UI is completely blind to what is present in the OS.

**Comment by johman10** [comment]
@niawag you're right something like that could be done as well! An interesting suggestion to also consider while implementing this.

In general I would want to make this quite diverse though, not to force the user to deal with the file system etc, but rather to allow at least some kind of UI to export and import the data. However that doesn't take away the option to also support a file system approach.

**Comment by matt8707** [comment]
> I'm using it with [transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn) as a docker container and I'd like to know if the exported json file could be mounted as a volume in docker so it could be easy to store these configs on the server.

@niawag same, this is my workaround

```bash
#!/bin/bash

# save user interface settings in flood
# type "localStorage" into console, right click and copy object
# paste object below into "const obj"

# https://haugene.github.io/docker-transmission-openvpn/config-options/#custom_scripts
# volume /path/transmission/scripts:/scripts
# chmod +x scripts/transmission-pre-start.sh

python3 << EOF
PATH = "/opt/transmission-ui/flood-for-transmission/index.html"

SCRIPT = r"""
  <script>

    const obj = {
        "ui-columns": "[{\"id\":13,\"enabled\":true,\"width\":363},{\"id\":27,\"enabled\":true,\"width\":100},{\"id\":15,\"enabled\":true,\"width\":300},{\"id\":9,\"enabled\":true,\"width\":100},{\"id\":6,\"enabled\":true,\"width\":100},{\"id\":22,\"enabled\":true,\"width\":100},{\"id\":10,\"enabled\":true,\"width\":100},{\"id\":1,\"enabled\":true,\"width\":185},{\"id\":7,\"enabled\":false,\"width\":100},{\"id\":23,\"enabled\":false,\"width\":100},{\"id\":14,\"enabled\":false,\"width\":100},{\"id\":19,\"enabled\":false,\"width\":100},{\"id\":2,\"enabled\":false,\"width\":100},{\"id\":3,\"enabled\":false,\"width\":100},{\"id\":4,\"enabled\":false,\"width\":100},{\"id\":11,\"enabled\":false,\"width\":100},{\"id\":16,\"enabled\":false,\"width\":100},{\"id\":12,\"enabled\":false,\"width\":100},{\"id\":8,\"enabled\":false,\"width\":100},{\"id\":21,\"enabled\":false,\"width\":100},{\"id\":18,\"enabled\":false,\"width\":100},{\"id\":5,\"enabled\":false,\"width\":100},{\"id\":20,\"enabled\":false,\"width\":100},{\"id\":17,\"enabled\":false,\"width\":100},{\"id\":24,\"enabled\":false,\"width\":100},{\"id\":25,\"enabled\":false,\"width\":100},{\"id\":26,\"enabled\":false,\"width\":100}]",
        "tableHeaderConfig": "false",
        "paths": "[]",
        "torrent-sorting": "{\"id\":13,\"direction\":\"asc\"}",
        "darkMode": "enabled",
        "switchSpeedColors": "false",
        "timeConfig": "true"
    }

    for (const [key, value] of Object.entries(obj)) {
        localStorage.setItem(key, value);
    }

  </script>
"""

with open(PATH, "r", encoding="utf-8") as file:
    content = file.read()
    file.close()

INJECT = content.replace("</head>", SCRIPT + "</head>")

with open(PATH, "w", encoding="utf-8") as file:
    file.write(INJECT)
    file.close()

EOF

```

**Comment by johman10** [comment]
@ivanjx @niawag @matt8707 as you might have noticed I have released a new version with at least some kind of server side configuration. This means you can effectively overwrite the default configuration.

So the order of importance is like this:
Client configuration > config.json configuration > original default configuration

PR for reference can be found here: https://github.com/johman10/flood-for-transmission/pull/540.

**Comment by niawag** [comment]
Thanks a lot for this release, I've tried it and I can see that my settings are propagated, great!
I'm having an issue with the common paths setting, I can see they are set well in the webui setting but, when I click on the magnifier icon to choose one, the webui get stuck, only a refresh works to get it back. I opened chrome console and here is the error:
```
Paths.svelte:18 Uncaught (in promise) TypeError: Pl.init is not a function
    at ic (Paths.svelte:18:15)
    at We (Component.js:148:34)
    at new ac (Paths.svelte:14:17)
    at ne (dom.js:1198:9)
    at Wa (ContextMenu.svelte:120:32)
    at Object.p (ContextMenu.svelte:102:20)
    at Ee (scheduler.js:119:30)
    at Se (scheduler.js:79:5)
```

Another little problem is that, once the webui is used on a client the following changes in config.json won't be propagated without clearing storage and autorisations (why are both needed ?) but I'm not sure this can be leveraged. Or is it possible to change the order of preference and always use config.json configuration?

**Comment by johman10** [comment]
Regarding the error, I just pushed a fix for that. I should probably write some tests at some point. 😅 

> Another little problem is that, once the webui is used on a client the following changes in config.json won't be propagated without clearing storage and autorisations (why are both needed ?) but I'm not sure this can be leveraged. Or is it possible to change the order of preference and always use config.json configuration?

Yeah, that's a limitation of the current setup. Perhaps easiest would be to prevent changes if a config file is present. But I don't really want to force everyone to use a file to configure the UI, hence why it's currently supported. Changing the priority order is another option, but I would have to find another way to store the column width than I'm doing currently for that to work correctly.

**Comment by niawag** [comment]
Great, thanks for the fix!
Would it be possible to store a hash of the file (or another way to check if the file changed) ? If yes, we could reload file and overwrite client config only if the file changed.
The column width is a very good example of what should **not** be in the config file, maybe a part of the settings like this one should be in another file, not affected by the presence of a config file.

**Comment by matt8707** [comment]
How does this work with haugene/transmission-openvpn? Linking [config.json](https://github.com/johman10/flood-for-transmission/blob/b495cc43a612ba26573b214e05e213a68aa8931b/public/config.json) has no effect, do i have to install flood manually?

```yaml
transmission:
  image: haugene/transmission-openvpn
  environment:
    TRANSMISSION_WEB_UI: flood-for-transmission
  volumes:
    - /volume1/docker/transmission/config.json:/opt/transmission-ui/flood-for-transmission/public/config.json
    ...

```

**Comment by johman10** [comment]
@matt8707 I think that should work. Can you share the output of the next two commands after running it on the Docker host machine:
```
ls -al /volume1/docker/transmission/config.json
docker exec transmission ls -al /opt/transmission-ui/flood-for-transmission/public/config.json
```

**Comment by matt8707** [comment]
```bash
-rwxrwxrwx+ 1 matte users 349 Nov 24 02:55 /volume1/docker/transmission/config.json
-rwxrwxr-x 1 abc abc 349 Nov 24 02:55 /opt/transmission-ui/flood-for-transmission/public/config.json
```

I also can't find a `config.json.defaults` file, which suggests that I might be on an older version? (haugene/transmission-openvpn is latest)

**Comment by johman10** [comment]
Right, that's probably it. You will have to wait for haugene/transmission-openvpn to upgrade to the latest version, but after that this mounting solution should work.

**Comment by niawag** [comment]
I think you should install this webui as an alternate webui, not messing with the flood installed by default. You just have to mount a volume with this webui file and change the TRANSMISSION_WEB_HOME to this path. This issue should help you do so: https://github.com/haugene/docker-transmission-openvpn/discussions/2271 (same problem for a different webui)

**Comment by matt8707** [comment]
Can confirm that new [docker-transmission-openvpn](https://github.com/haugene/docker-transmission-openvpn/releases/tag/v5.3.1) release has the config.json.defaults

Using public folder, linking config  file still has no effect. I did clear localStorage, console says

> No config.json found, using default values:
See https://github.com/johman10/flood-for-transmission#beta-customization


What did fix it was to remove public in the path 👍🏻 

```bash
volumes:
  - /volume1/docker/transmission/config.json:/opt/transmission-ui/flood-for-transmission/config.json
```
