### ISSUE TITLE
Filter by priority

### ISSUE THREAD

**Issue by realivanjx** [johman10/flood-for-transmission#446]
i want to be able to filter by priority (low, normal, high). i download torrents weekly and i want to give higher priority to those weekly torrents i downloaded and reset them to normal at the end of the week. i think it would be easier to do it if i can do filter by priority. thanks.

**Comment by johman10** [comment]
This should be fairly straightforward to add. I'm assuming you want a filter like there is filters for labels, status and trackers? :)

**Comment by realivanjx** [comment]
yes. low, normal, and high.
