### ISSUE TITLE
Set labels doesn't work

### ISSUE THREAD

**Issue by J0ins08** [johman10/flood-for-transmission#493]
When I try to set some labels by right-click a torrent - set labels,  after I enter labels and click the "Set labels" button, these labels will be shown in the label filter well, but they have not shown in the Details - General - Labels yet. If I flash the site, all the labels I set will become undefined in label filter.

**Comment by johman10** [comment]
This is probably because you're running Transmission 2.x instead of version 3.x. 2.x does not have support for labels.

Please update to 3.x and let me know if it resolves your issue.

**Comment by J0ins08** [comment]
> This is probably because you're running Transmission 2.x instead of version 3.x. 2.x does not have support for labels.
> 
> Please update to 3.x and let me know if it resolves your issue.

It works well after I update to 3.0. :)
Thank you so much for your prompt reply and your great job.
