### ISSUE TITLE
priority filter does not work well with other filters

### ISSUE THREAD

**Issue by realivanjx** [johman10/flood-for-transmission#497]
![image](https://user-images.githubusercontent.com/12814796/187133292-4211c32d-30bf-43c6-928d-9d238f91f03e.png)

already selected All but nothing is being shown. if i select either High or Normal then it will show up.

![image](https://user-images.githubusercontent.com/12814796/187133466-d3dc7ad9-be0e-4634-80be-00ff42d1f41f.png)

**Comment by johman10** [comment]
Good catch! Silly mistake from my end. Thank you for the PR!
