### ISSUE TITLE
Disable Upload Speed in user interface breaks the graph

### ISSUE THREAD

**Issue by trinsic** [johman10/flood-for-transmission#50]
I know this probably seems trivial but when you disable 'upload speed' in the user interface tab it will break the download/upload graph, setting upload to "undefined".

**Comment by johman10** [comment]
Interesting! I haven't noticed this myself. I'm pretty certain I tried to account for this type of setup.

I will try to reproduce this and get back to you ASAP.

**Comment by johman10** [comment]
This should have been resolved as per: https://github.com/johman10/flood-for-transmission/commit/a3e9397686725e782d25835d44b0b6d1b9efe645.

Please pull, rebuild and restart transmission to see the result. :)
