### ISSUE TITLE
Bug Report

### ISSUE THREAD

**Issue by J0ins08** [johman10/flood-for-transmission#500]
1. Settings -> Network

Click the 'Save settigns' button in 'Network' setting page, the alert shows 'Succesfully saved torrent settings' or 'Failed saving torrent settings, please try again'. Should the word 'torrent' in these alerts will be 'network'?

2.Settings -> User Interface

When click the 'Save settings' button after checked the 'Total Leechers' or 'Total Seeders' column in 'Torrent Columns', the alert shows nothing and the console logs 'Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')'. At that time, the other columns can not be checked or unchecked, I can't go to the other setting pages or close the UI page either but flash the web site.

**Comment by johman10** [comment]
@J0ins08 thanks a lot for the issue. As you can see these issues should now be resolved. Let me know if you experience further issues by opening a new one.
