### ISSUE TITLE
Flood ui breaking sonarr & radarr integration ?

### ISSUE THREAD

**Issue by P6g9YHK6** [johman10/flood-for-transmission#520]
if enabled it prevent radarr and sonarr to see if a download is completed. (*arr will show the correct "100%" but not the status "completed")
and will not import the files once downloaded.

i tried restarting all my containers to no avail...
the only solution was to disable the mod.

#https://github.com/linuxserver/docker-mods/issues/586

**Comment by johman10** [comment]
I wouldn't know how this theme via the mod would cause this kind of issue.

I also answered in the other thread. Let's continue the discussion there.

**Comment by P6g9YHK6** [comment]
Tried to reproduce the issue and it is working now.
i have just reenabled flood and everything is importing fine.

I havent done anything to correct the previous behaviors so i am closing this for now  :/
