### ISSUE TITLE
Flood over Docker (Synology NAS)

### ISSUE THREAD

**Issue by gmeroni** [johman10/flood-for-transmission#521]
Hello guys, I am having difficulty setting up this new UI. As you can see from the screenshots I've set up the Env variable, placed the file, and mounted the path but still no luck. What am I missing? 

![2023-03-07 10_53_01-192 168 178 52_9091_transmission_web_ and 29 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/14147510/223387273-124a7416-5f51-4541-8ce1-fface70e2b2d.png)

![2023-03-07 10_53_26-Portainer _ local and 29 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/14147510/223387281-ec876b7b-1606-41f3-9522-7a3bc117d8e5.png)

![2023-03-07 10_54_06-DS923 - Synology NAS and 29 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/14147510/223387284-1289a3d4-c815-40b1-97b5-c9b1602eae0f.png)

![2023-03-07 10_56_28-DS923 - Synology NAS and 29 more pages - Work - Microsoft​ Edge](https://user-images.githubusercontent.com/14147510/223387843-5ebf6848-9163-42aa-b63c-a0dc04e2e64a.png)

**Comment by Svision** [comment]
Your mapped path to container is /flood-for-transmission but your environment is set to /docker/transmission/ui/flood-for-transmission
