### ISSUE TITLE
Stats refresh requests time is too small?

### ISSUE THREAD

**Issue by cpainchaud** [johman10/flood-for-transmission#524]
Hi,

 Great work you've done here, I love your interface. I noticed one thing though, it seems to request an update from rpc several times per second. I like when things are efficient and avoid unecessary load on machines, do you think you could lower this to once a second or better make it configurable?

thank you!

**Comment by johman10** [comment]
I went with one second because of personal preference. I also believe the default Transmission UI uses 1 second as the polling interval.

However, this can of course be made configurable. I can have a look at this at some point. But also feel free to contribute.

**Comment by cpainchaud** [comment]
thank you for your reply, I see that the UI is hitting 2 or 3 times per seconds ... hmm

**Comment by johman10** [comment]
> I see that the UI is hitting 2 or 3 times per seconds ... hmm

Do you mean the default Transmission UI? Or Flood for Transmission? There are multiple requests going to the RPC API for different purposes, some are updating the torrent list, others are fetching more details for a specific torrent, some are fetching the statistics.

As long as Transmission doesn't support any kind of open connection (WebSockets or Server Sent Events) there is no real other way (apart from making it configurable).

Please notice that these requests will only be made as long as you have the UI open. As soon as you close the tab, the requests will stop.
