### ISSUE TITLE
Peers Flags all unknown

### ISSUE THREAD

**Issue by LiFE1688** [johman10/flood-for-transmission#526]
Hi, firstly, would like to say flood-for-transmission is my go to for Transmission BT WebUI, I wouldn't be using Transmission if there wasn't this UI. Great job.

When checking each torrent, under Peers tab, all the country flags for peers show up as a ? flag, unknown.

Not sure if you are aware of this issue.

Thanks.

**Comment by johman10** [comment]
@LiFE1688 are you using some kind of ad blocker? If so try to disable it. I have experienced the same thing when using Ublock Origin and disabling it resolved the issue.

Please check and let me know here if it worked.

**Comment by LiFE1688** [comment]
You are right, I disabled Pihole and it worked.
What is the domain that is required, would be easier to just put it in the whitelist.

Thanks.

**Comment by LiFE1688** [comment]
Nevermind, I found it.
get.geojs.io

Thank you again.
