### ISSUE TITLE
Torrent with thousands of files, unable to find/filter file due to weird sorting order!

### ISSUE THREAD

**Issue by cchhat01** [johman10/flood-for-transmission#529]
Seems like the sorting order goes for a toss, it seems to be sorting using the file size in descending order, with the completed ones on the top. That order is useless to me if I am looking for a file with a specific name within that torrent.
See screenshot below.
![Web capture_5-5-2023_22290_192 168 1 11](https://user-images.githubusercontent.com/14076520/236594232-d44065e0-5bae-4b1a-a63c-89c9c845b40e.jpeg)

**Comment by johman10** [comment]
I believe currently this isn't sorted at all. I understand that can be annoying. I can probably change the sorting fairly easily.

Thank for the feedback!
