### ISSUE TITLE
Installing on FreeBSD / TrueNAS jail

### ISSUE THREAD

**Issue by ivanovd** [johman10/flood-for-transmission#535]
Does anyone have a guide on how to install Flood for Transmission inside a FreeBSD 13 jail on TrueNAS? I tried with the public_html folder replacement with the one from the release branch but that didn't work -> it still loads the old interface

**Comment by johman10** [comment]
@ivanovd isn't TrueNAS supporting any kind of docker image? If so you can run the [linuxserver.io docker image](https://hub.docker.com/r/linuxserver/transmission) and add the [Flood For Transmission mod](https://hub.docker.com/r/linuxserver/mods).

**Comment by ivanovd** [comment]
@johman10 unfortunately there is no native support for it, as far as I know. It uses jails (which is the Docker alternative in FreeBSD). The only way to run a docker container is to spin up an Ubuntu virtual machine and install docker on it, however that consumes a lot of resources which I'd like to avoid.

**Comment by johman10** [comment]
I see!

> I tried with the public_html folder replacement with the one from the release branch but that didn't work
Can you clarify how you replaced the public_html content?

**Comment by ivanovd** [comment]
@johman10 good question. I thought that I have replaced the files in the correct public_html folder, but it seems that there were two public_html folders and I have replaced the files in the wrong one. I have replaced the files in the correct one now and all is working fine.

/usr/local/share/transmission/public_html is the correct folder in case someone comes across the same issue

```
root@Transmission:~/Transmission/web/public_html # find / -name public_html
/root/Transmission/web/public_html
/usr/local/share/transmission/public_html
root@Transmission:~/Transmission/web/public_html # ls -l /root/Transmission/web/public_html
total 146
-rw-r--r--  1 root  wheel     238 Aug  1 18:10 browserconfig.xml
drwxr-xr-x  2 root  wheel      19 Aug  1 18:10 build
-rw-r--r--  1 root  wheel      25 Aug  1 18:10 config.json
drwxr-xr-x  7 root  wheel       8 Aug  1 18:10 fonts
drwxr-xr-x  4 root  wheel       5 Aug  1 18:10 images
-rw-r--r--  1 root  wheel    1290 Aug  1 18:10 index.html
-rw-r--r--  1 root  wheel     477 Aug  1 18:10 manifest.webmanifest
drwxr-xr-x  2 root  wheel       5 Aug  1 18:10 style
-rw-r--r--  1 root  wheel    2198 Aug  1 18:10 sw.js
-rw-r--r--  1 root  wheel    3846 Aug  1 18:10 sw.js.map
-rw-r--r--  1 root  wheel   14302 Aug  1 18:10 workbox-d249b2c8.js
-rw-r--r--  1 root  wheel  137332 Aug  1 18:10 workbox-d249b2c8.js.map
root@Transmission:~/Transmission/web/public_html # ls -l /usr/local/share/transmission/public_html
total 119
drwxr-xr-x  2 root  wheel       5 Jul 31 20:15 images
-rw-r--r--  1 root  wheel    9137 Jul 31 19:53 index.html
-rw-r--r--  1 root  wheel  217332 Jul 31 19:53 transmission-app.js
-rw-r--r--  1 root  wheel     468 Jul 31 19:53 transmission-app.js.LICENSE.txt
```

Many thanks :)
