### ISSUE TITLE
Not Working on Mac with Transmission 4.0.4

### ISSUE THREAD

**Issue by mslmn** [johman10/flood-for-transmission#536]
I followed the install instructions for Mac but when I restart Transmission it still uses the default webui.

**Comment by johman10** [comment]
Too bad it's not working. Could you show the output of:
`ls /Applications/Transmission.app/Contents/Resources/web`

**Comment by johman10** [comment]
Aha! Please copy all data from `flood-for-transmission` into the web folder:
```
cp /Applications/Transmission.app/Contents/Resources/web/flood-for-transmission/* /Applications/Transmission.app/Contents/Resources/web/
```

I think then it should start working. Also make sure you restart Transmission to ensure it loads the new files correctly.

**Comment by johman10** [comment]
Just to clarify: which UI are you seeing and expecting to change?

Perhaps the web UI has moved, could you run: `find /Applications/Transmission.app -name index.html`

**Comment by johman10** [comment]
So I guess the UI has moved within the app could you check with:
`ls /Applications/Transmission.app/Contents/Resources/public_html`

If it lists stylesheets and JavaScript files etc you can try to run the command from the readme (don't skip over the backup) but replace `/web` with `/public_html`.

**Comment by johman10** [comment]
I would like to keep this ticket open as a reminder for me to update the README.
