### ISSUE TITLE
torrents sorting

### ISSUE THREAD

**Issue by adiadi2** [johman10/flood-for-transmission#550]
Hi, is it possible to sort torrents by age, 'm I blind?
Love the skin but missing sorting.
ty

**Comment by johman10** [comment]
Hi!
You can sort by any of the columns that you can find in the settings => User Interface.

Currently "age" is not one of those, I will keep this issue open to add support for that value as a column at some point.

**Comment by johman10** [comment]
@jamesharding is correct actually, the "age" that you're requesting is either created or added. Which are already present in the UI.

If you want to sort by a specific column you have to make sure it's shown by selecting the column in the "User Interface settings". Once you have the column you can click on the column header to sort by the column either ascending or descending.

I will close this issue now as it became clear that it's already supported.
