### ISSUE TITLE
Speedlimit unit text-wrap

### ISSUE THREAD

**Issue by defkev** [johman10/flood-for-transmission#554]
Just upgrade to latest release on my notebook and dunno if this is new or i just never noticed it before but the units (e.g. MB/s) gets wrapped on next line in the sidebar if speed limit is enabled:

![Screenshot 2024-01-30 at 08-05-25 Flood - Transmission](https://github.com/johman10/flood-for-transmission/assets/5265345/a279a93f-abad-4297-b120-b7c92e2510eb)

Fix is trivial:
```css
.limit span {
    white-space: nowrap;
}
```
in `src/components/Graph/SpeedLimit.svelte`

![Screenshot 2024-01-30 at 08-06-19 Flood - Transmission](https://github.com/johman10/flood-for-transmission/assets/5265345/55b46d8b-9f3c-4c7e-be02-b8faddbd7696)

Tested on current FF v122

**Comment by johman10** [comment]
As you can see above this is now resolved. Thanks a lot for taking the time to open the issue!
