### ISSUE TITLE
Regression: fileIndex is off

### ISSUE THREAD

**Issue by defkev** [johman10/flood-for-transmission#555]
Changing the priority of a single file (in Files.svelte) changes it for a different file (e.g. index off by -2), i assume this is related to 18a11d1386a2ca8bf446f1d8aab5f5ba255b0646 since this did definitely work before the latest version.

Edit: After pulling current master and commenting the change i can confirm this is definitely a regression

**Comment by johman10** [comment]
As you can see above this is now resolved. Thanks a lot for taking the time to open the issue!
