### ISSUE TITLE
Flood in Docker return 404

### ISSUE THREAD

**Issue by amirzenoozi** [johman10/flood-for-transmission#564]
Hi Guys, I have a problem using the flood. I update the configs very well. But it returned 404 because the flood-for-transmission return access was denied. And I had something like this: 
Can you help me to solve this:

![image](https://github.com/johman10/flood-for-transmission/assets/16349391/8726140a-d81c-4015-bf01-370acfab0888)

**Comment by greenfishgit22** [comment]
I have the same issue, except mine says "flood-for-transmission/index.html (No such file or directory)" after updating transmission to the most recent version.

**Comment by johman10** [comment]
Which docker image are you using? In the screenshot there seems to be a typo for `/root/**t**ransmission` it seems like there is a problem with the Docker image and not with Flood for Transmission. Please open an issue on the docker image side to get this resolved.

**Comment by amirzenoozi** [comment]
@johman10 
I fixed the type, But the problem still exists.
I used `lscr.io/linuxserver/transmission:latest` as a Transmission docker image.
I hope you can help me.

**Comment by amirzenoozi** [comment]
@johman10 
Which Docker image should I choose to use `Flood-for-transmission`.

**Comment by johman10** [comment]
Could you try to set the version to 4.0.5-r0-ls224? Does that one work?

**Comment by johman10** [comment]
Are you using the docker mod as specified in the readme here?
https://github.com/linuxserver/docker-mods/tree/transmission-floodui

**Comment by amirzenoozi** [comment]
> Are you using the docker mod as specified in the readme here? https://github.com/linuxserver/docker-mods/tree/transmission-floodui

Changing the Version of the docker image doesn't work but this one does. 
Thanks for your help.

**Comment by greenfishgit22** [comment]
Can someone tell me how to use  https://github.com/linuxserver/docker-mods/tree/transmission-floodui.

I tried adding DOCKER_MODS=linuxserver/mods:transmission-floodui in the docker-compose.yml for transmission but I get "ERROR: yaml.scanner.ScannerError: while scanning a simple key"
