### ISSUE TITLE
Lockfile no longer includes some native rollup dependencies

### ISSUE THREAD

**Issue by al3xtjames** [johman10/flood-for-transmission#571]
https://github.com/johman10/flood-for-transmission/commit/97c666ccd6c6f24abbda982dd5dd5ff217db9784 dropped some of the native rollup dependencies in `package-lock.json` for various platforms, including `darwin-x64`. AFAICT this will break the build on those platforms with the existing lockfile. It seems ilke this might be caused [by an npm bug](https://github.com/npm/cli/issues/4828)?

**Comment by johman10** [comment]
Thank you for opening the issue @al3xtjames! I will try to have a look at this more thorougly this week!
