### ISSUE TITLE
Broken file selector

### ISSUE THREAD

**Issue by TougeAI** [johman10/flood-for-transmission#575]
The webui file chooser isn't passing the correct file index to the client. Here I've set 1 folder of a multi-folder torrent to download, but the result is just two files are downloaded as the ui is passing a sequential block (see 3rd screenshot) and not what actually belongs to that folder (which is shown in the 2nd screenshot).

Latest flood-ui (https://github.com/johman10/flood-for-transmission/commit/782e5c54b7287a1020fa43c170ca1c5824f9e755)
Transmission 4.0.5

1. <img width="135" alt="webui" src="https://github.com/johman10/flood-for-transmission/assets/94567978/31aeec77-81a0-47e7-8ae9-4129fed39276">

2. <img width="206" alt="actual folder in transmission cli" src="https://github.com/johman10/flood-for-transmission/assets/94567978/b90bd1c3-b8d7-4812-b763-155ec7dc71d8">

3. <img width="206" alt="what the webui passed to transmission" src="https://github.com/johman10/flood-for-transmission/assets/94567978/8dfe018a-d7fe-46b7-9d72-ed17bf7c470a">

**Comment by johman10** [comment]
I aimed to fix this with https://github.com/johman10/flood-for-transmission/commit/5f2ec4419506b37b103656a5e01808f94943f561. But it seems like it didn't work... I will have to have another look, but if you have any ideas on how to resolve this please feel free to open a pull request!

**Comment by johman10** [comment]
@TougeAI I tried to reproduce this on the latest version but it's not working. Are you 100% sure you're running the latest version? 

How are you running the UI? Do you happen to be running it as part of a docker container? If so you will have to wait for a new release from the docker image to get the latest version of the UI as building the UI is part of the Dockerfile which will only executed upon building the image.

Please let me know whether updating the UI fixes the issue for you.

**Comment by digdug3** [comment]
Have the same issue. `transmission-daemon 4.0.6+dfsg-1`
When selecting files to download the last one wasn't downloaded.

**Comment by johman10** [comment]
This took me a while to understand, but I landed on a solution that seems to work. I will still release this in an official release this week. I hope it works for you, let me know if it doesn't.
