### ISSUE TITLE
Discord Notification - Webhook

### ISSUE THREAD

**Issue by Nautilus34** [johman10/flood-for-transmission#580]
Hello,

I would like to receive notifications when a torrent is added or finished. 
Is it possible to implement a webhook feature for this?

Additionally, I have a question about the download/upload history displayed in the top left. 
Is there a way to disable it ?

Thank you for your help.

**Comment by johman10** [comment]
Hi @Nautilus34,
Sadly this UI this is not possible. This UI is only generating HTML that Transmission will serve, so as soon as you close the browser there is nothing running anymore. This means it can't keep track of the status of torrents, let alone send out notifications.

If you're intestested in a feature like this I would recommend to open an issue for Transmission itself: https://github.com/transmission/transmission.
