### ISSUE TITLE
feature request： add option of transmission-remote localhost -e [size］

### ISSUE THREAD

**Issue by c0ldian** [johman10/flood-for-transmission#585]

**Comment by johman10** [comment]
@c0ldian, I don't fully understand what you're requesting here, but it sounds like you're requesting to filter the torrents. This is already implemented in the UI, see the screenshot below on where to do so: ![image](https://github.com/user-attachments/assets/a445ae5f-6077-4958-84fd-5af38f0e2967).

This doesn't support regex, but it does support any character and filters out any irrelevant characters.
