### ISSUE TITLE
mobile ui is missing

### ISSUE THREAD

**Issue by derekn** [johman10/flood-for-transmission#67]
the original Flood project has a mobile/responsive view, which appears to be missing in this project. is this a bug or intentional?

**Comment by johman10** [comment]
This is kind of intentional for now. I haven't spend any time on making this project responsive. However, it shouldn't be too hard. The main thing to resolve would be the sizes of the modal that open up and how there content wraps I believe.

For now life is a little busy for me and I'm still working on a dark mode. But I will consider this for sure in the future.

**Comment by derekn** [comment]
gotcha, makes sense. dark mode is definitely important too.
appreciate all the hard work, and look forward to the updates

**Comment by fLyRhyTHeMz** [comment]
any updates on this. absolutely love how flood looks on desktop, but have reverted to combustion b/c of the mobile layout.

**Comment by johman10** [comment]
@fLyRhyTHeMz no updates really. I haven't done any work on this yet. I will let you know here when it's done.

Life is quite filled with other things for me right now but I will focus on this when I have some time for it.

**Comment by johman10** [comment]
I'm sorry everyone. I didn't get around to this yet. But I'm going to start working on this now. So please hang tight and you will find this issue closed soon! :smile:

**Comment by johman10** [comment]
Hey! I have a branch open with some changes. If anyone wants to try it out, that would be great! Feedback is appreciated.

You can find the branch here: https://github.com/johman10/flood-for-transmission/tree/mobile-ui.

There are still some things left to do and I will get to those soon before shipping it into a release. ;)

**Comment by johman10** [comment]
This was now released. Feel free to try it out and let me know if you experience any issues!

**Comment by fLyRhyTHeMz** [comment]
Is there any mechanism by which this update for mobile to be deployed via the transmission-openvpn docker container? That's where I was looking to use the mobile ui.

**Comment by johman10** [comment]
@fLyRhyTHeMz I think restarting the docker container will redownload flood-for-transmission at it's latest version. I'm however not 100% certain.

**Comment by PleaseStopAsking** [comment]
@fLyRhyTHeMz Once https://github.com/haugene/docker-transmission-openvpn releases a new image, it will automatically get the newest release from this repo. If you want it sooner, the only method would be to build the image yourself using the provided Dockerfile and use that in the mean time.

There is a new request to have the image automatically build anytime there are upstream releases. https://github.com/haugene/docker-transmission-openvpn/issues/1832#issue-896923014

**Comment by ksurl** [comment]
you can also have it download the latest build with a custom script in `/scripts//scripts/transmission-pre-start.sh`
